### ISSUE TITLE
ValueError: time data '2017-05-03 06:00:29 +0200' does not match format '%Y-%m-%d %H:%M:%S UTC'

### ISSUE THREAD

**Issue by Tontonitch** [stdevel/check_katello_sync#2]
Hello, 
Apparently I'm facing a date format issue:
```
-bash-4.2$ /usr/lib64/nagios/plugins/check_katello_sync.py -s xxxxx -o yyyyy -a /usr/lib64/nagios/plugins/katello.auth
Traceback (most recent call last):
  File "/usr/lib64/nagios/plugins/check_katello_sync.py", line 354, in <module>
    main(options)
  File "/usr/lib64/nagios/plugins/check_katello_sync.py", line 339, in main
    check_products()
  File "/usr/lib64/nagios/plugins/check_katello_sync.py", line 148, in check_products
    check_product(product)
  File "/usr/lib64/nagios/plugins/check_katello_sync.py", line 106, in check_product
    product["last_sync"], "%Y-%m-%d %H:%M:%S UTC"
  File "/usr/lib64/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '2017-05-03 06:00:29 +0200' does not match format '%Y-%m-%d %H:%M:%S UTC'
-bash-4.2$ 
```
Is there a way to fix that?
BR,
Yannick

**Comment by stdevel** [comment]
Also applicable to https://github.com/stdevel/check_katello_currency/issues/4

**Comment by stdevel** [comment]
Hello Yannick,
tried to fix this in commit fb3c10f037cfe8dd556780857349dde6bbd964a2 - can you check it?

Best regards,
Christian.

**Comment by stdevel** [comment]
Thanks for your feedback!
